[build]
  base = "frontend/job-tracker-frontend"
  command = "CI=false npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://jobtracker-backend-production-ea98.up.railway.app/api"