[build]
  base = "frontend/job-tracker-frontend"
  command = "CI=false npm run build"
  publish = "frontend/job-tracker-frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
