# netlify.toml for Job Tracker Frontend
[build]
  base = "."                   # Base directory for build commands
  publish = "build"            # Folder to publish
  command = "npm run build"    # Build command

[context.production.environment]
  # Backend API URL
  REACT_APP_API_URL = "https://jobtracker-backend-production-ea98.up.railway.app"


